apiVersion: apps/v1
kind: Deployment
metadata:
  name: jagdish-elasticsearch
  namespace: jagdish-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jagdish-elasticsearch
  template:
    metadata:
      labels:
        app: jagdish-elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        resources:
          requests:
            memory: "2Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        env:
        - name: discovery.type
          value: single-node
