apiVersion: v1
kind: ConfigMap
metadata:
  name: jagdish-filebeat-config
  namespace: jagdish-elk
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/*.log

    output.logstash:
      hosts: ["jagdish-logstash:5044"]
