apiVersion: v1
kind: ConfigMap
metadata:
  name: jagdish-logstash-config
  namespace: jagdish-elk
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["http://jagdish-elasticsearch:9200"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      }
    }
