apiVersion: apps/v1
kind: Deployment
metadata:
  name: jagdish-logstash
  namespace: jagdish-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jagdish-logstash
  template:
    metadata:
      labels:
        app: jagdish-logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.10.0
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: logstash-config
        configMap:
          name: jagdish-logstash-config
